<?xml version="1.0"?>
<robot name="basic_robotic_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Include inertial macros -->
  <xacro:include filename="inertial_macros.xacro"/>

  <!-- Properties -->
  <xacro:property name="arm_length" value="1.0"/>
  <xacro:property name="arm_radius" value="0.05"/>
  <xacro:property name="base_height" value="0.1"/>
  <xacro:property name="base_mass" value="1.0"/>
  <xacro:property name="link_mass" value="0.5"/>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.2 0.2 ${base_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.2 0.2 ${base_height}"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="${base_mass}" x="0.2" y="0.2" z="${base_height}">
      <origin xyz="0 0 ${base_height / 2}" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>

  <!-- Arm Link 1 -->
  <link name="link1">
    <visual>
      <geometry>
        <cylinder length="${arm_length}" radius="${arm_radius}"/>
      </geometry>
      <material name="green"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${arm_length}" radius="${arm_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${link_mass}" length="${arm_length}" radius="${arm_radius}">
      <origin xyz="0 0 ${arm_length / 2}" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <!-- Joint 1 -->
  <joint name="joint1" type="revolute">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-1.57" upper="1.57" effort="10.0" velocity="1.0"/>
  </joint>

  <!-- Arm Link 2 -->
  <link name="link2">
    <visual>
      <geometry>
        <cylinder length="${arm_length}" radius="${arm_radius}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${arm_length}" radius="${arm_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${link_mass}" length="${arm_length}" radius="${arm_radius}">
      <origin xyz="0 0 ${arm_length / 2}" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <!-- Joint 2 -->
  <joint name="joint2" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 ${arm_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="10.0" velocity="1.0"/>
  </joint>

</robot>
