# This is an empty file, so that git commits the folder correctlyjoint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

joint1_position_controller:
  type: position_controllers/JointPositionController
  joint: joint1
  pid: {p: 10.0, i: 0.1, d: 0.01}

joint2_position_controller:
  type: position_controllers/JointPositionController
  joint: joint2
  pid: {p: 10.0, i: 0.1, d: 0.01}
